fastfloat/fast_float

include/fast_float/ascii_number.h
include/fast_float/float_common.h
include/fast_float/simple_decimal_conversion.h

During library integration into ClickHouse https://github.com/ClickHouse/ClickHouse/pull/16787 we had a couple of ODR violations during link time.

Fixed odr with inlining and anonymous namespace

---

include/fast_float/decimal_to_binary.h

Minor simplification.

---

.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20.yml
.github/workflows/vs16-ci.yml
.github/workflows/vs16-clang-ci.yml
.gitignore
.travis.yml
AUTHORS
CMakeLists.txt
include/fast_float/float_common.h
tests/CMakeLists.txt
tests/basictest.cpp
tests/long_random64.cpp
tests/random64.cpp

add 32bit version

---

include/fast_float/simple_decimal_conversion.h

Fixes https://github.com/fastfloat/fast_float/issues/47

Fixes issue 47

---

tests/basictest.cpp

https://github.com/wrandelshofer/FastDoubleParser/issues/7

Add test corresponding to issue in wrandelshofer / FastDoubleParser

---

include/fast_float/ascii_number.h

Added 8-digit optimizations to big endian.

---

include/fast_float/float_common.h

Adding m_arm detection.

---

.github/workflows/vs16-cxx20.yml
include/fast_float/ascii_number.h
include/fast_float/decimal_to_binary.h
include/fast_float/fast_float.h
include/fast_float/float_common.h
include/fast_float/parse_number.h
include/fast_float/simple_decimal_conversion.h
tests/basictest.cpp

This removes CXX 20 support since it is incorrect and untested.

Removing CXX20 support

---

include/fast_float/parse_number.h

Fixing https://github.com/fastfloat/fast_float/issues/154
(A release will follow.)

Fixing issue 154.

---

include/fast_float/fast_float.h
include/fast_float/fast_table.h

Add missing namespace end comments

---

.github/workflows/amalgamate-ubuntu20.yml
.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20-fastmath.yml
.github/workflows/ubuntu20.yml

(This PR changes nothing, it just removes ugly scripting code.)

Cleaning our CI a bit.

---

include/fast_float/float_common.h

float_common.h: add support for ppc32

---

include/fast_float/ascii_number.h
include/fast_float/float_common.h
include/fast_float/parse_number.h
tests/CMakeLists.txt
tests/rcppfastfloat_test.cpp

We enable some features that rccpfastfloat might need, and we add some extra tests.

Support rccpfastfloat via macros

---

.github/workflows/alpine.yml
include/fast_float/parse_number.h
tests/basictest.cpp

Fixes https://github.com/fastfloat/fast_float/issues/174

Trying to extend alpine CI to more systems and fixing legacy issue (x86)

---

include/fast_float/bigint.h
include/fast_float/float_common.h

In this PR I applied constexpr in all functions in float_common.h and big_int.h . The plan is to eventually mark everything constexpr, but maybe it does not need to happen in a single PR.

Constexpr big_int

---

README.md
tests/example_test.cpp

This documents the new compile-time feature.
Credit to @leni536 for all the hard work.

Compile-time evaluation

---

include/fast_float/float_common.h

Fixes https://github.com/fastfloat/fast_float/issues/211

Renaming the using for the local type.

---

README.md
include/fast_float/ascii_number.h
include/fast_float/float_common.h
tests/CMakeLists.txt
tests/fortran.cpp
tests/json_fmt.cpp

Cleaned up version of https://github.com/fastfloat/fast_float/pull/219 by @allenbarnett5

Fortran support (with fixes)

---

include/fast_float/float_common.h

check C++ standard version before including <stdfloat>

---

include/fast_float/ascii_number.h

Fixes https://github.com/fastfloat/fast_float/issues/244

removing unused function

---

include/fast_float/decimal_to_binary.h

As a follow up to  #216 . It's not branchless, but, nevertheless, allow to extract part of the logic so it can be reused.
Running the benchmark shows no difference in term of instruction count, branch and whatnot with the previous code.

Extract the round to even loigic so it can be reused for hex floats.

---

.github/workflows/ubuntu24.yml
include/fast_float/decimal_to_binary.h

update CI to ubuntu 24 + safe a shift value to a variable (for elegance)

---

.clang-format
.github/pull_request_template.md
.github/workflows/lint_and_format_check.yml
script/run-clangcldocker.sh

add linter

---

tests/BUILD.bazel
tests/CMakeLists.txt
tests/supported_chars_test.cpp
tests/unicode_test.cpp

Add basic tests for all supported char types (char, wchar_t, char8_t, char16_t, char32_t)

Add tests for all supported char types

---

.github/workflows/ubuntu24.yml
CMakeLists.txt
benchmarks/CMakeLists.txt
benchmarks/apple_arm_events.h
benchmarks/benchmark.cpp
benchmarks/event_counter.h
benchmarks/linux-perf-events.h

It would be useful to refer contributors to our own benchmarks.

adding actual benchmarks to the project
