.github/workflows/msys2.yml
.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20.yml

re #34: reproduce in CI

---

.travis.yml
include/fast_float/ascii_number.h
include/fast_float/float_common.h
include/fast_float/parse_number.h

Fixes https://github.com/lemire/fast_float/issues/37

Adding support for big endian systems

---

include/fast_float/decimal_to_binary.h
include/fast_float/float_common.h
tests/exhaustive32.cpp
tests/exhaustive32_64.cpp
tests/exhaustive32_midpoint.cpp
tests/long_exhaustive32.cpp
tests/long_exhaustive32_64.cpp
tests/long_random64.cpp
tests/random64.cpp
tests/random_string.cpp
tests/short_random_string.cpp
tests/string_test.cpp

Picking up on the discussion started on #23 about large binaries: it is definitely real. This is what I'm seeing on the size harness [that I detailed on that discussion](https://github.com/lemire/fast_float/issues/23#issuecomment-727620113):
```shellsession
[jpmag@pc] 3039$ for i in * ; do echo "$i/`cat $i/bm/float/*fast_float_d*dat`" ; done
linux-x86_64-clangxx11.0-Debug/c4core-bm-readfloat-fast_float_d: {compile: 0.343s, file_size: 1447312B}
linux-x86_64-clangxx11.0-Release/c4core-bm-readfloat-fast_float_d: {compile: 0.353s, file_size: 1391776B}
linux-x86_64-gxx10.2-Debug/c4core-bm-readfloat-fast_float_d: {compile: 0.318s, file_size: 1451928B}
linux-x86_64-gxx10.2-Release/c4core-bm-readfloat-fast_float_d: {compile: 0.203s, file_size: 1391768B} …
```

remove 1.1MB (85%) of binary size by not including iostream

---

include/fast_float/float_common.h

Looking into https://issues.apache.org/jira/browse/ARROW-11501, we found that this change was necessary to compile on Solaris (though perhaps not sufficient, haven't gotten that far yet).

Locate endian header on Solaris

---

include/fast_float/parse_number.h

Parse "nan(n-char-seq-opt)" as required by C++17 20.19.3.7 and C11 7.20.1.3.3.
At least MSVC produces nan(ind) and nan(snan), and according to https://reviews.llvm.org/D70631 MSVC implementation seems to became LLVM std::to_chars().
float => string => float roundtripping was tested for all floats on macOS with custom "charconv" header that includes https://reviews.llvm.org/D70631 patch that added std::to_chars(... float/double ...) capability.

Parse "nan(n-char-seq-opt)" as required by C++17 20.19.3.7

---

include/fast_float/decimal_to_binary.h
include/fast_float/parse_number.h
include/fast_float/simple_decimal_conversion.h

As it was proposed in #54, this PR changes anonymous namespaces to `detail`, but only for functions.
There are still variables that get duplicated in compilation units, also outside of the anonymous namespace. The biggest of them is `power_of_five_128`. It'd think it might be UB, but IANAL (in particular not a C++ language lawyer).
For power_of_five I'd be for using the template trick that allows inline variables in C++11, as described in [this answer][1] and as [used in sajson][2].
[1]: https://stackoverflow.com/a/38043566/104453
[2]: https://github.com/chadaustin/sajson/blob/3f256a9b1771e480fe363fb7bef9e847de8eb92a/include/sajson.h#L137

change anonymous namespace to namespace detail (#54)

---

include/fast_float/decimal_to_binary.h
include/fast_float/fast_table.h
include/fast_float/simple_decimal_conversion.h

Should be self-explanatory.
Alternative to https://github.com/fastfloat/fast_float/pull/67
cc @wojdyr

This uses the template trick to ensure we get only one definition

---

.github/workflows/ubuntu20.yml
.github/workflows/vs16-ci.yml
tests/CMakeLists.txt
tests/build_tests/CMakeLists.txt
tests/build_tests/issue72/CMakeLists.txt
tests/build_tests/issue72/foo.cpp
tests/build_tests/issue72/main.cpp
tests/build_tests/issue72/test.h
tests/installation_tests/issue72_installation/CMakeLists.txt

This will build an executable matching the description of issue 72.

Checking issue 72

---

include/fast_float/float_common.h

Fixes #76.
This was tested via emulation on the following systems:
- alpha
- i686
- mips64r6el
- ppc64
- sh4
- arm64
- m68k
- mips
- ppc64le
- sparc64
- armel-armhf
- mips64
- mipsel
- ppc
- armel
- mips64el
- mipsr6
- riscv64
- hppa
- mips64r6
- mipsr6el
- s390x
All systems passed except for M68K and HPPA. For M68K, the only differences were the NaN values (which is trivial), while with HPPA, there was a core dump (more severe, but it's a rare architecture), and a new version has not been released in over 25 years.
The Dockerfile and CMake toolchains can be found [here](https://github.com/Alexhuszagh/toolchains).

Add support for other architectures.

---

.travis.yml
ci/script.sh

This fixes the [comments](https://github.com/fastfloat/fast_float/pull/77#issuecomment-847240467) on PR #77, by adding CI support for 2 of the most important architectures fixed by #77.
There are potential downsides here, in that it relies on Docker images [here](https://hub.docker.com/r/ahuszagh/cross/tags?page=1&ordering=last_updated), which are build from [Alexhuszagh/toolchains](https://github.com/Alexhuszagh/toolchains). This has a few disadvantages, since I am not a maintainer of `fast_float` (nor do I intend to be), but the CI would then depend on my own Docker images.
A few simple alternatives are:
1. Provide your own Docker images on Dockerhub.
2. Copy the Dockerfiles and build if `TOOLCHAIN` is set on each CI build.
The second would make the CI builds much slower, but would …

Add support for MIPS64 and RISCV64 on CI.

---

tests/CMakeLists.txt

This option is off by default, maintaining the previous behavior. When
enabled (along with FASTFLOAT_TEST), it bypasses the FetchContent
machinery for doctest so that a system-wide installation of the doctest
header can be easily used. In this case, the header doctest/doctest.h
should be available on the compiler’s include path.
This option is especially useful for Linux distributions and others that
need to run the tests in fully offline build environments.
Fixes #83.
(This a trivial change, which I believe is not subject to copyright protection. Accordingly, I do not need to be added to the CONTRIBUTORS file.)

Add a SYSTEM_DOCTEST CMake option

---

.github/workflows/amalgamate-ubuntu20.yml
CONTRIBUTORS
README.md
script/amalgamate.py

This PR contains an amalgamate script that generates a single include file.
The script concatenates various files in the repository including authors, contributors, license (can choose from cli), and the various header files in the order of include, and removing local `#include` directives. The formatting I choose is just what I found easy to do on the first run by can be customized by changing easily by changing the script.
We can handle single includes in two manners: (1) provide a script that needs to be run by the library user, or (2) provide the amalgamated files ourselves. In the former case, the library is a bit harder to use. In the latter case, we need to add complexity to the CI setup. For example, do we include single header tests and installation? For now, I have decided to …

Single include script

---

include/fast_float/ascii_number.h

Fixes #94, by replacing unspecified pointer comparisons with well-defined behavior using `std::distance` with the current pointer and the pointer to one-past-the-end of the array.
As a simple schematic of why this is important, we have:
```text
| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
| x | x | x | p | - | - | - | - | - | - | - | - |
```
As you can if we have already the `x` digits, with an array with `10` elements, and try to compare `p+8` to `pend`, we compare after the end of the array. This could optimize to being always true, or the integer arithmetic could wrap, leading to another always-true comparison.
The conformant solution is therefore: `std::distance(p, pend) >= 8`, which also [optimizes](https://godbolt.org/z/aqvThfqac) well, so there's no issue of a performance hit (just …

Fixes #94, with unspecified behavior in pointer comparisons.

---

include/fast_float/ascii_number.h
include/fast_float/decimal_to_binary.h
include/fast_float/fast_float.h
include/fast_float/float_common.h
include/fast_float/parse_number.h
include/fast_float/simple_decimal_conversion.h
tests/basictest.cpp

Tested with GCC11 and little endian only.
To test it, change `set(CMAKE_CXX_STANDARD 11)` to `set(CMAKE_CXX_STANDARD 20)` in the CMakeLists.txt. Seems like this cannot be overriden from command line. 
To prove compile time parsing works, I added a few `static_asserts` in `basic_test.cpp`. You can make sure they actually work by changing the numbers and see them fail. ;)
**Changes**:
Apart from all the added constexpr, the only actual changes are inside `read_u64` and `write_u64`. Some constants are now `constexpr` instead of `static const`.
**Compiler support detection**:
constexpr is added to lots of functions if  `__cpp_lib_bit_cast` define is available. If it is not available, `CXX20_CONSTEXPR` is reduced to nothing.

constexpr for c++20 compliant compilers

---

include/fast_float/ascii_number.h
include/fast_float/decimal_to_binary.h
include/fast_float/fast_table.h
include/fast_float/parse_number.h

From issue #97 :
- remove `<cstdio>` includes, they seem unused (I assume they are relicts from debugging), compiles without them
- remove `<cassert>` include from `parse_number.h`, there is no assert (only static_assert)
- add esthetic newlines between include guards and includes 
Is `fast_table.h` auto generated? Apparently I added a newline to the last line (like all other files have).

Remove unneeded includes

---

tests/CMakeLists.txt
tests/basictest.cpp
tests/example_comma_test.cpp
tests/example_test.cpp
tests/exhaustive32.cpp
tests/exhaustive32_64.cpp
tests/exhaustive32_midpoint.cpp
tests/long_exhaustive32.cpp
tests/long_exhaustive32_64.cpp
tests/long_random64.cpp
tests/long_test.cpp
tests/powersoffive_hardround.cpp
tests/random64.cpp
tests/random_string.cpp
tests/short_random_string.cpp
tests/string_test.cpp

This moves tests with ~subsecond durations from the exhaustive test suite (which does not run in CI) to the default suite (which does). We also configure `long_test.cpp` (which was abandoned) to be in the default test suite and apply two fixes to it to make it compile and pass (`#include <iostream>` to make `std::cerr` etc. be defined, and apply the same whitespace-skipping fix we used in `string_test.cpp`).

Testing changes and fixes

---

include/fast_float/digit_comparison.h
include/fast_float/float_common.h

Fix the following warning:
```
/arrow/cpp/src/arrow/vendored/fast_float/digit_comparison.h:62:50: error: right shift count >= width of type [-Werror=shift-count-overflow]
am.power2 = int32_t((bits & exponent_mask) >> binary_format<T>::mantissa_explicit_bits());
~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Fix #117: compilation warning with gcc 6.3.0

---

include/fast_float/float_common.h

The current check for endianness fails on platforms using newlib as the
C library, because it provides <machine/endian.h> not <endian.h>. This
could be fixed by adding `|| defined(__NEWLIB__)` to the check for
targets that provide <machine/endian.h> (i.e. BSD-like targets).
A more portable solution is to just check if the compiler has already
defined the necessary macros (which is true for GCC and Clang and Intel,
at least). Then no header is needed, and it works for platforms that
aren't explicitly listed in the conditionals.

Make endianness detection more portable

---

include/fast_float/digit_comparison.h

This assumes that the literal `64` of type `int` has the same type as the `int32_t` typedef, which is never true for targets with 16-bit `int`, and isn't guaranteed to be true even with 32-bit `int`.

Fix deduction failure for std::min call

---

.github/workflows/vs17-arm-ci.yml
.github/workflows/vs17-ci.yml
.github/workflows/vs17-clang-ci.yml
.github/workflows/vs17-cxx20.yml

It appears that vs16 is no longer supported under GitHub actions.

Trying to upgrade to vs17

---

CMakeLists.txt

Export CMake targets as architecture independent.
This will fix issues when package was built on 32-bit and then reused on 64-bit architectures and fixes the following issues:
```
CMake Error at CMakeLists.txt:52 (find_package):
Could not find a configuration file for package "FastFloat" that is
compatible with requested version "".
The following configuration files were considered but not accepted:
/usr/share/cmake/FastFloat/FastFloatConfig.cmake, version: 3.4.0 (32bit)
```
`ARCH_INDEPENDENT` requires CMake 3.14 or higher, that's why we use version check.

Export CMake targets as architecture independent

---

script/amalgamate.py

- on some containers LC_ALL is not set, python fallback on ascii
encoder, which fails on _AUTHORS_ file

python: set file encoding

---

.github/workflows/alpine.yml
.github/workflows/amalgamate-ubuntu20.yml
.github/workflows/msys2-clang.yml
.github/workflows/msys2.yml
.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20-cxx20.yml
.github/workflows/ubuntu20.yml
.github/workflows/vs17-arm-ci.yml
.github/workflows/vs17-ci.yml
.github/workflows/vs17-clang-ci.yml
.github/workflows/vs17-cxx20.yml

Updates the `actions/checkout` action used in the GitHub Actions workflow to its newest version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.0.2
> - [Add input `set-safe-directory`](https://github.com/actions/checkout/pull/770)
>
> ## v3.0.1
> - [Fixed an issue where checkout failed to run in container jobs due to the new git setting `safe.directory`](https://github.com/actions/checkout/pull/762)
> - [Bumped various npm package versions](https://github.com/actions/checkout/pull/744)
>
> ## v3.0.0
>
> - [Update to node 16](https://github.com/actions/checkout/pull/689)
As far as I can tell this should all be backwards compatible, so I do not expect any breakage.

update actions/checkout in GitHub Actions to v3

---

include/fast_float/float_common.h

I'm not familiar with MinGW on ARM64 but it seems that `__umulh()` isn't available with MinGW on ARM64.
See also: https://github.com/msys2/MINGW-packages/pull/12508
Note that `__MINGW32__` is defined with both of 32bit and 64bit MinGW.

Don't use __umulh() with MinGW on ARM64

---

CMakeLists.txt

When using fast_float as a PRIVATE dependency, it is not required to install it. This flag give user using fastfloat with add_subdirectory the opportunity to disable install target Default behavior is conserved since FASTFLOAT_INSTALL is ON
PR #142 is proposing the same change, mine differ by also using `CMAKE_INSTALL_INCLUDEDIR` to give user more control over installation

🔨 Introduce FASTFLOAT_INSTALL to make install optional

---

CMakeLists.txt
include/fast_float/ascii_number.h

This PR balances the performance trade-off differently. Credit to @mwalcott3 for raising the issue.
We use https://github.com/lemire/simple_fastfloat_benchmark as a reference.
Current code (main branch):
```
-f data/canada.txt
fastfloat                               :  1289.31 MB/s (+/- 0.9 %)    74.09 Mfloat/s      17.71 i/B   323.23 i/f (+/- 0.0 %)      2.59 c/B    47.30 c/f (+/- 0.6 %)      6.83 i/c      3.50 GHz 
-f data/canada_short.txt
fastfloat                               :   543.83 MB/s (+/- 0.5 %)   101.04 Mfloat/s      41.34 i/B   233.29 i/f (+/- 0.0 %)      6.15 c/B    34.68 c/f (+/- 0.2 %)      6.73 i/c      3.50 GHz 
-f data/mesh.txt
fastfloat                               :   863.78 MB/s (+/- 1.4 %)   117.67 Mfloat/s      26.42 i/B   203.39 i/f (+/- 0.0 %)      3.87 c/B …
```

Trimming out one eight-digit optimization.

---

.github/workflows/ubuntu20-fastmath.yml
include/fast_float/bigint.h
include/fast_float/float_common.h
include/fast_float/parse_number.h
tests/CMakeLists.txt
tests/basictest.cpp

As remarked by @jakubjelinek, we cannot unconditionally use the conventional Clinger's fast path because it assumes that the rounding mode is set to 'nearest' (which is the universal default). Now, nothing stops a user from changing the rounding mode, but we need our code to produce the same result (rounding to nearest) irrespective of the system's rounding mode.
Checking that `fegetround() == FE_TONEAREST` is too expensive on some systems.
A better solution was proposed by  @mwalcott3  and involves doing an addition, a subtraction and a comparison to verify that the rounding mode is set to nearest. Because parsing a float might already involve hundreds of instructions, this check is relatively cheap. The resulting branch is also invariably well predicted.
This allows us to bring back the …

Conditional Clinger's fast path

---

include/fast_float/fast_table.h

Do not use UTF-8 character '−'. It causes warning if the default encoding of compiler is not UTF-8 (mainly MSVC).

Replace utf8 chars.

---

include/fast_float/decimal_to_binary.h
script/mushtak_lemire.py

We can slightly simplify the algorithm.
- Noble Mushtak, Daniel Lemire,  [Fast Number Parsing Without Fallback](https://arxiv.org/abs/2212.06644), Software: Practice and Experience (to appear)

We do not need a fallback.

---

include/fast_float/float_common.h

* Use right-sized uint type for bit fiddling
* This removes the need to special casing on endianness
* Replace ternary with just shifting the sign at the right place
* This seems to improve codegen (less instructions, no cmov)
Codegen demonstration:
gcc 12: https://godbolt.org/z/ceYK4crde
clang 15: https://godbolt.org/z/WTcqn8xGv
MSVC 19.14: https://godbolt.org/z/P3d8dv9Eq

Simplify to_float

---

include/fast_float/parse_number.h

This issue was detected via https://github.com/redis/redis/actions/runs/4349106283/jobs/7598380101 , specifically the part of `zadd ztmp +inf x`
The error is related to the +inf parsing. After checking parse_infnan we can indeed confirm that the '+' sign is not being checked and the str position is updated accordingly. This PR addresses it.

Added missing FASTFLOAT_ALLOWS_LEADING_PLUS ifdef check in parse_infnan

---

include/fast_float/parse_number.h
tests/basictest.cpp

I added new tests for parsing -0 in all rounding modes. This fails on clang on main.

Fix parsing -0 on clang in non-nearest rounding modes.

---

tests/basictest.cpp

Fixes GCC 9 fast-math test fail from https://github.com/fastfloat/fast_float/pull/189
See successful Actions run: https://github.com/alugowski/fast_float/actions/runs/4580158419

Fix subnormal test fails on GCC 9

---

.github/workflows/ubuntu22-clang.yml
.github/workflows/ubuntu22-gcc12.yml
.github/workflows/ubuntu22.yml
README.md
include/fast_float/decimal_to_binary.h
script/amalgamate.py
script/mushtak_lemire.py
tests/example_comma_test.cpp
tests/exhaustive32.cpp
tests/exhaustive32_64.cpp
tests/exhaustive32_midpoint.cpp
tests/installation_tests/find/CMakeLists.txt
tests/long_exhaustive32.cpp
tests/long_exhaustive32_64.cpp
tests/long_random64.cpp
tests/long_test.cpp
tests/powersoffive_hardround.cpp
tests/random64.cpp
tests/random_string.cpp
tests/short_random_string.cpp
tests/string_test.cpp

Release 4.0 broke some of the disabled-by-default tests due to an API change. This PR should fix them.
Fix https://github.com/fastfloat/fast_float/issues/191

We need to update some of our exhaustive tests to the new API

---

include/fast_float/ascii_number.h
include/fast_float/constexpr_feature_detect.h
include/fast_float/float_common.h
include/fast_float/parse_number.h

- `FASTFLOAT_ALLOWS_LEADING_PLUS` and `FASTFLOAT_SKIP_WHITE_SPACE` are not defined by default, and compiling with `-Wundef` is emitting warnings like "FASTFLOAT_ALLOWS_LEADING_PLUS is not defined, evaluates to 0".
- Likewise for `FASTFLOAT_VISUAL_STUDIO`, change checks to use #ifdef for that like in other places.
- `__cpp_lib_bit_cast` and `__cpp_lib_is_constant_evaluated` are not defined pre-C++20, and are emitting a warning too.

Fix warnings with -Wundef

---

include/fast_float/float_common.h

Some tables were left as `static`. It's problematic due to two reasons:
* It may cause unnecessary bloat when multiple TUs use `from_chars`.
* It's technically ODR violation of the inline functions using these tables.
In this PR I make these tables static members of a class template and I create static constexpr references to them so they remain accessible through their original names. This is a pattern to emulate `inline` variables before C++17.

Make tables external linkage

---

.gitignore
include/fast_float/fast_float.h
include/fast_float/float_common.h
include/fast_float/parse_number.h
script/amalgamate.py

Intellisense is broken with this library, making it almost impossible to work on in Visual Studio. VS2017 to VS2022 are all affected.
This cause of this issue was reported 6 years ago: https://developercommunity.visualstudio.com/t/intellisense-breaks-for-header-files-if-not-includ/92374, but the VS team said they had no plans to fix it.
This PR applies a fix that has worked for me in past projects i.e. a file should include all definitions it uses.
"constexpr_feature_detect.h", <system_error>, and from_chars types (from_chars_result, parse_options etc.) should be included in every file to be seen by Intellisense (instead of just once in fast_float.h).

Fix for broken VS Intellisense

---

.github/workflows/on-release.yml

This workflow runs automatically when a new release is created. It creates the amalgamated `fast_float.h` and adds it as a release asset to the newly-created release.
It uses the creation and test code from https://github.com/fastfloat/fast_float/blob/main/.github/workflows/amalgamate-ubuntu20.yml
See result here: https://github.com/alugowski/fast_float/releases/tag/test

Add on-release workflow

---

include/fast_float/float_common.h

LoongArch is a new architecture that is already supported by linux-6.1, gcc-12, and I want to add LoongArch support for fast_float.

float_common.h: Support LoongArch64

---

include/fast_float/ascii_number.h
include/fast_float/float_common.h

This is an obvious follow-up to the work done by @mayawarrier in https://github.com/fastfloat/fast_float/pull/198
I am getting a nice performance bump on the canada test (Apple M2, LLVM 14):
Before:
```
fastfloat                               :  2328.12 MB/s (+/- 1.3 %)    66.89 Mfloat/s       9.40 i/B   343.05 i/f (+/- 0.0 %)      1.44 c/B    52.42 c/f (+/- 0.7 %)      6.54 i/c      3.51 GHz
```
After:
```
fastfloat                               :  2617.00 MB/s (+/- 1.4 %)    75.20 Mfloat/s       8.60 i/B   313.66 i/f (+/- 0.0 %)      1.28 c/B    46.63 c/f (+/- 0.7 %)      6.73 i/c      3.51 GHz
```
Possibly, it could be further improved because NEON is far superior to SSE2, but it is already decent.

ARM NEON optimization (UTF-16 inputs)

---

.gitignore
include/fast_float/ascii_number.h

When using msvc v140 (Visual Studio 2015 Toolset), compilation fails.

Fix broken msvc v140

---

include/fast_float/float_common.h

Xcode 15 is showing warnings when including fast_float. See screenshot.
That warning says that the comma is meant to return a value, but that value is unused, so that code style is discouraged. I've reverted the code style to the previous one (partial revert of #180), and replaced the remaining commas with semicolons.

float_common.h: fix possible misuse of comma operator

---

.github/workflows/cifuzz.yml

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This service is offered by OSS-Fuzz where fast_float already runs. CIFuzz can help catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
I added a similar PR in a related repository, which I think have some overlap in maintainers (https://github.com/simdutf/simdutf/pull/262)

Add CIFuzz workflow

---

include/fast_float/ascii_number.h
include/fast_float/float_common.h
include/fast_float/parse_number.h
tests/CMakeLists.txt
tests/json_fmt.cpp

Details on the format are available here (RFC 8259): https://datatracker.ietf.org/doc/html/rfc8259#section-6
This is compatible with previous JSON RFCs as well as the number format hasn't changed.

Add support for parsing numbers according to JSON format

---

include/fast_float/ascii_number.h
include/fast_float/float_common.h
tests/CMakeLists.txt
tests/fortran.cpp

Hi: I'm working on a program which reads an input file which is ordinarily read by a Fortran program. Numbers in the input are converted to binary with the Fortran internal read function. For example, 
CHARACTER(LEN=25) :: CHARS
REAL(KIND=8) :: NUMBER
READ ( CHARS, '(e25.0)' ) NUMBER
The Fortran internal read accepts a larger variety of formats than std::from_chars. In particular, the 'E' in the exponent is optional (!); it can also be replaced with a 'D'. A leading '+' is also accepted. So, "+1+1" is 10.
I made a few changes to fast_float to support this case. I realize it's somewhat out of scope for a C++ function, but it is useful to me.  fast_float is much better than my attempt.
I added a test, but no other CMake infrastructure. Since it does add a condition in parse_number_string, I …

Allow fast_float to parse strings accepted by the Fortran internal read function.

---

include/fast_float/float_common.h

Fix an analyzer warning from Xcode 15.

float_common.h:237:52 Value stored to 'input_num' is never read

---

include/fast_float/parse_number.h

In some cases, Visual Studio, when compiling 32-bit binaries, gets 0*something == -0 even when the 'something' is positive, if the system is not set to round to nearest.
(This is very narrow and I can't reproduce it locally. The patch is a precaution.)

fix for 32-bit Visual Studio when not set to round to nearest

---

include/fast_float/float_common.h

I think FASTFLOAT_ARM64 is meant to be FASTFLOAT_NEON here.
Without this, FASTFLOAT_HAS_SIMD doesn't get defined for ARM targets, and ARM SIMD doesn't get used in the parser.

Fix for ARM SIMD

---

.github/workflows/vs17-ci.yml
CMakeLists.txt
README.md
include/fast_float/ascii_number.h
include/fast_float/parse_number.h
tests/CMakeLists.txt
tests/fast_int.cpp

This PR implements the C++17 function:
from_chars_result from_chars( const char* first, const char* last, /* integer-type */& value, int base = 10);
- Implementation is similar to that in #86.
- Uses SIMD acceleration for base 10.
Tests contributed by @TheRandomGuy146275.
Resolves #86

from_chars integer parser

---

tests/CMakeLists.txt
tests/basictest.cpp

As the supplemental_test_files are quite large, it is useful to make running the tests depending on it optional.
By default, the tests are kept enabled, but can be switched of by setting `FASTFLOAT_SUPPLEMENTAL_TEST=OFF`.
Fixes: #232

Make tests depending on supplemental_test_files optional

---

.github/workflows/ubuntu22-sanitize.yml
fuzz/from_chars.cc
include/fast_float/ascii_number.h
include/fast_float/parse_number.h
tests/CMakeLists.txt
tests/fast_int.cpp

When an integer string begins and end with zeroes, we may read beyond the scope.
Fixes https://github.com/fastfloat/fast_float/issues/235

Verify and fix issue 235

---

CMakeLists.txt

Hi there, I would like to ask if is possible to update version in order to sent this patch to [downstream](https://gitlab.archlinux.org/archlinux/packaging/packages/fast_float/-/issues) because if this digits are different generates issues, for example for https://aur.archlinux.org/packages/ants#comment-960051 or any project that has `find_package(VTK)` and has `fast_float-6.1.0`.

Use version 6.1.0 instead 6.0.0

---

include/fast_float/float_common.h

I noticed a compilation error when building a 64-bit binary with this library while using xlclang on AIX, and this change seems to fix it.

Add a missing check that __uint128_t exists before using it.

---

include/fast_float/float_common.h

`18446744073709551615e-65` rounds to `0`, and it is the largest possible value with exponent `-65`. Therefore, we can assume the minimal exponent for which we don't round to zero actually is `-64`.

Change smallest_power_of_ten to -64 for floats.

---

include/fast_float/parse_number.h

Idea is to split parsing from value computation adding a from_chars_advanced function taking result of parsing.

from_chars_advanced overload function taking parsed_number_string_t

---

include/fast_float/ascii_number.h
tests/json_fmt.cpp

Revert #251, and instead allow an invalid trailing empty exponent to be
treated as junk data in JSON parsing. Expand the test suite to test this
case, including testing the trailing junk.

Allow JSON empty exponent as trailing junk

---

include/fast_float/ascii_number.h
tests/json_fmt.cpp

In parse_number_string, if there is a parse error, report the specific
error as one of the values in a new parse_error enum, and update
lastmatch to match the error location. This allows users of the library
to print more helpful error messages for invalid inputs.

Record parse failure reason and location

---

include/fast_float/float_common.h

Arm64 uses __umulh, so add the same condition for including the intrin.h header.
This was failing when trying to pull fast_float into Chromium (https://ci.chromium.org/ui/p/chromium/builders/try/win-arm64-compile-dbg/131424/overview)

Include intrin.h for __umulh

---

README.md
tests/example_test.cpp

fixes https://github.com/fastfloat/fast_float/issues/261 by documenting it.
We follow @jwakely's and Microsoft's interpretation of the standard.
We will not be changing the behaviour of the library unless someone from the C++ standard says that we are wrong.

documentation for issue 261

---

include/fast_float/float_common.h

The patch resolves GCC compilation issues for the C++ language targeting
aarch64-w64-mingw32.
More information could be found here:
https://gcc.gnu.org/pipermail/gcc-patches/2024-September/662020.html

Support aarch64-w64-mingw32 target

---

tests/CMakeLists.txt

Hi, I've been working on [packaging](https://github.com/spack/spack/pull/46137) fast-float for Spack, including tests. Since Spack aims to avoid vendored dependencies, it installs doctest separately in its own prefix and not in the system location. By adding a `find_package(doctest)` statement, as recommended in the [doctest documentation](https://github.com/doctest/doctest/blob/master/doc/markdown/build-systems.md), fast-float can successfully locate the package, allowing us to build and run the tests properly. 
I made minimal changes to easily patch older versions.

doctest: if SYSTEM_DOCTEST add a `find_package(doctest REQUIRED)`

---

script/amalgamate.py

When adding the license text, only add leading whitespace to non-empty lines, otherwise it becomes trailing whitespace.
Tested with each `--license` option to verify the only changes in the generated output are removing the unwanted trailing whitespace.

Prevent amalgamate.py from adding trailing whitespace

---

.bazelrc
.gitignore
BUILD.bazel
MODULE.bazel
tests/BUILD.bazel
tests/basictest.cpp
tests/fixedwidthtest.cpp

Similar to https://github.com/lemire/fast_double_parser/pull/79, I would like to contribute this excellent library to Bazel. Please take a look.
`build --cxxopt="--std=c++17"` set in `.bazelrc` only affects the tests. When the library is imported by other project, they can specify whatever C++ version.

Add Bazel build rules.

---

CONTRIBUTORS
include/fast_float/ascii_number.h
include/fast_float/parse_number.h
tests/rcppfastfloat_test.cpp

"-+NNNN" should fail to parse, regardless of what NNNN is and regardless if FASTFLOAT_ALLOWS_LEADING_PLUS is defined.
Fixes #276

Issue276 plus/minus handling in parse_infnan

---

include/fast_float/ascii_number.h
include/fast_float/float_common.h
include/fast_float/parse_number.h

Changed chars_format to an enum class.
Added operators to comply to [BitmaskType](https://en.cppreference.com/w/cpp/named_req/BitmaskType).
Fixes #278

enum class chars_format

---

README.md
include/fast_float/ascii_number.h
include/fast_float/fast_float.h
include/fast_float/float_common.h
include/fast_float/parse_number.h
tests/BUILD.bazel
tests/CMakeLists.txt
tests/fortran.cpp
tests/json_fmt.cpp
tests/rcppfastfloat_test.cpp
tests/wide_char_test.cpp

* Add allow_leading_plus and skip_white_space in chars_format
* Fix fastfloat_strncasecmp and is_space for wchar_t and larger char types
Fixes #275

Add allow_leading_plus and skip_white_space in chars_format

---

include/fast_float/float_common.h

Add version macros

---

include/fast_float/fast_float.h
include/fast_float/float_common.h
include/fast_float/parse_number.h

Better compile time error messages for unsupported types

---

README.md
include/fast_float/float_common.h

Support char8_t on C++20

---

.clang-format
benchmarks/apple_arm_events.h
benchmarks/event_counter.h
include/fast_float/bigint.h
include/fast_float/digit_comparison.h
include/fast_float/fast_float.h
include/fast_float/float_common.h
include/fast_float/parse_number.h
tests/basictest.cpp
tests/build_tests/issue72/foo.cpp
tests/build_tests/issue72/main.cpp
tests/exhaustive32_midpoint.cpp
tests/fixedwidthtest.cpp
tests/json_fmt.cpp
tests/powersoffive_hardround.cpp
tests/random_string.cpp
tests/short_random_string.cpp
tests/string_test.cpp

* introduce equiv_uint_t helper
* harmonize ifdef checks
* formatted code

introduce equiv_uint_t helper

---

include/fast_float/ascii_number.h

This code caused a C4127 "conditional expression is constant" compiler warning when compiled with Visual Studio at warning level 4 with T a signed integer type.

Silenced Visual Studio compiler warning

---

.github/pull_request_template.md
README.md

documenting benchmarks

---

.github/workflows/ubuntu24.yml
benchmarks/event_counter.h
include/fast_float/float_common.h

Fixes a warning when `-Wundef` is used.

fix warning from -Wundef

---

CMakeLists.txt

When using the library with Clang on Windows (not clang-cl and not MSYS2), an error is thrown by the compiler:
```
clang: error: no such file or directory: '/permissive-'
```
This is caused by these lines in `CMakeLists.txt`:
```cmake
if(MSVC_VERSION GREATER 1910)
target_compile_options(fast_float INTERFACE /permissive-)
endif()
```
Clang on Windows defines `MSVC_VERSION`, but does not support MSVC-like compiler flags. This PR adds an extra check to make sure the flag is only added when the used compiler supports it.
Presumably fixes #304, although it seems that CI only has MSYS2 Clang and MSVC Clang-cl workflows, neither of which are impacted by this issue, so I've only verified that it works on my machine.

fix /permissive- flag causing a compile error on clang for windows

---

benchmarks/benchmark.cpp
include/fast_float/ascii_number.h
include/fast_float/constexpr_feature_detect.h
include/fast_float/parse_number.h
tests/json_fmt.cpp

We have added a few options (such as  json_fmt). These trigger a short series of branches in our `parse_number_string` function. Unfortunately, this is costing us a bit of performance. We can get it back by turning the runtime parameters into template parameters... there is still a branch, but it is more direct and likely extremely cheap.
Building:
```
cmake -B build -D FASTFLOAT_BENCHMARKS=ON
cmake --build build
```
Let us benchmark on an Apple M2 processor (LLVM 16). These benchmarks are part of our library.
Before:
```
⚡  ./build/benchmarks/realbenchmark
####
####
ASCII volume = 1.93374 MB
fastfloat (64)                          :  1166.05 MB/s (+/- 8.5 %)    67.01 Mfloat/s
fastfloat (32)                          :  1211.52 MB/s (+/- 7.5 %)    69.62 Mfloat/s
UTF-16 volume = 3.86749 MB …
```

turning json option into macro parameter

---

README.md

Add a reference to the AK library used by SerenityOS and Ladybird.
This implementation is used for LibJS and LibWeb, the ECMAScript and Web Engine for the two projects respectively. It is also used in SerenityOS's LibC.
Added in: https://github.com/SerenityOS/serenity/pull/15377
fwiw, there is also a Ryu printf implementation in AK/StringFloatingPointConversions.cpp
cc @davidot @danshaders

README: Reference SerenityOS/Ladybird Browser implementation

---

README.md

Hello
fast_float is now part of [xmake](https://xmake.io) repository here: https://github.com/xmake-io/xmake-repo/blob/dev/packages/f/fast_float/xmake.lua

README: Add xmake repository reference

---

README.md

The fast_float packaging is named differently across different Linux distros. Repology has consolidated that to a single page which is different than the page used in this project's README.md. This fixes that.

README.md: update repology badge
